FROM php:7.4-apache-buster

RUN apt-get update && apt-get -y install \
                                  default-mysql-client \
                                    vim \
                                    wget \
                                    curl \
                                    zsh \
                                    git \
                                    libzip-dev \
                                    gnupg \
                                    libmemcached-dev \
                                    zlib1g-dev \
        && docker-php-ext-install -j$(nproc) pdo_mysql\

    && apt-get clean && rm -rf /var/lib/apt/lists/*



RUN pecl install zip-1.15.4 \
              && pecl install xdebug-2.7.1 \
              && pecl install redis \
               # && pecl install memcached-2.2.0 \
  && docker-php-ext-enable  zip xdebug redis



#Installation Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --version=1.8.5
RUN php -r "unlink('composer-setup.php');"
RUN mv composer.phar /usr/local/bin/composer


#activeer rewrite op apache
RUN a2enmod rewrite


ENV APACHE_LOG_DIR /var/log/apache2


RUN useradd -ms /bin/bash jevdheyd
RUN usermod -a -G jevdheyd www-data
RUN usermod -a -G www-data jevdheyd

RUN echo "alias _xdebug='export PHP_IDE_CONFIG=\"serverName=localhost\" && export XDEBUG_CONFIG=\"remote_enable=1 remote_mode=req remote_port=9000 remote_host=172.17.0.1 remote_connect_back=0\"'" >>  /home/jevdheyd/.bashrc

RUN echo "alias _xdebug_profile='\"profiel_enable=1\"'" >>  /home/jevdheyd/.bashrc

RUN sed -ie 's/# alias ll=/alias ll=/g' /home/jevdheyd/.bashrc

RUN { \
          echo 'set nu'; \
          echo 'syntax on'; \
     } >>  /home/jevdheyd/.vimrc

RUN apt-get -y install zlib1g-dev

RUN mkdir -p /usr/src/php/ext \
    && cd /usr/src/php/ext \
    && git clone https://github.com/NoiseByNorthwest/php-spx.git \
    && cd php-spx/ \

COPY ./spx.ini /usr/local/etc/php/conf.d/

RUN cd /usr/src/php/ext/php-spx && phpize && ./configure

RUN docker-php-ext-install php-spx
